### ISSUE TITLE
Suggestions de corrections

### ISSUE THREAD

**Issue by LoganTann** [L-Sherry/French-CC#1]
(Je ne sais pas s'il faut parler français ou anglais, mais vu qu'il s'agit d'un projet de traduction français, autant rester sur cette langue :man_shrugging:)

Bonjour,
Je tiens tout d'abord à vous remercier pour le début de projet que vous faites. Cela doit demander un certain effort, en tant que moi-même fan-traducteur, et cela fait plaisir de voir les commits se succéder de jour en jours.

J'ai testé vos traductions en version du 15 juin dernier (c'est à dire que je n'ai pas mis à jour les fichiers de traductions depuis cette date). J'ai fait un léger test sur le passage de Shizuka et j'ai joué normalement au jeu en continuant ma progression actuelle (fin du chapitre 6 -> chapitre 8 en cours).

Voici des fautes que j'ai pu remarquer; je n'ai malheureusement pas de captures d'écran, je me suis juste contenté de noter sur un petit carnet.

- Thé feuilles vert -> "Thé vert" suffit (gain de place)
- "rond de pain" -> "miche de pain" ou tout simplement "pain" est plus commun.
- botaniques -> "botanique", le singulier suffit car il désigne l'ensemble de cette science.
- Vieux os -> "Vieil os"

Il y a certaines corrections que j'ai noté mais dont je me souviens plus telles que :
- (modificateur) prends ça : il manquait sans doute le S à prend. Une faute récurrente dans les traductions est le manque du s dans la conjugaison de la seconde personne du singulier.
- tien**s** encore : sans doute un problème d'accord/conjugaison

Dialogues : 
- (shizuka) : où est t-il -> où est-il.
- Qu'est ce que tu crois que tu fais -> "Que crois-tu faire" ou bien "Qu'est-ce que tu crois faire"
- C'est ce que tu aime dire -> oubli du s dans tu aimes
- Ça n'aurai jamais dû arriver -> Ça devrait être au conditionnel, donc il faut mettre un t à la fin du "aurai" sinon cela donne du futur simple.
- Dans ton état -> "Dans cet état" passe mieux dans le contexte.
- (chapitre 7) Pourquoi est ce que tu l'as mis dans une couverture -> il faut un tiret : "est-ce que"
- Elle ne devrai ; (plus loin) on voudrai; (encore plus loin) j'aimerai -> Conditionnel (il faut ajouter un t ou un s)
- attérir -> atterrir
- Ce qui allait arriver -> "ce qui allait t'arriver" (contexte)
- Attend -> Attends
- Comment vous avez atterri là -> Comment avez-vous atterri là; ou comment vous en avez atterri là ? (ces formes insistent sur une question)
- Qu'on à vu -> pas d'accent avec le a puisqu'il s'agit du verbe avoir
- ils aurraient -> ils auraient
- je supporte pas -> je ne supporte pas
- s'il te plait -> l'accent sur le i est plus commun (s'il te plaît)
- peut-être que tu peux faire voir -> "pourrais faire voir" passe mieux
- toucher rapidement deux mots -> "toucher deux mots rapidement" 
- secoue la tête -> hoche la tête
- *il est soit machin,* soit ~~est~~ virtuel -> le second est n'est pas obligatoire.
- oké -> okay/Ok est plus commun. Oki est aussi commun sur internet, à voir...
- routine -> assez technique... "fonction"/"sous-programme" serait plus parlant pour un joueur.
- n'essaye pas -> "n'essaie pas" cette seconde forme est plus commune
- agile et lour -> agile et lourd 
- on a des perroquets -> "nous avons des perroquets" paraît plus naturel
- arose -> arrose
- ces paresseux sont très rapide -> rapide prend un s
- absence de majuscules en début de certaines phrases

Et voilà !
Comme vous avez pu le remarquer, les principales fautes sont liées à la formulation malgré certaines fautes d'orthographe et de conjugaison. Lorsqu'on fait une traduction, il faut faire le juste milieu entre fiabilité de la traduction et aisance à la lecture. En bref, il faut que le joueur lise les dialogues sans avoir à s'arrêter pour relire ou remarquer une incohérence.
Ces erreurs sont très communes au début (je parle par expérience) mais avec de l'entrainement, on acquiert facilement la technique !

Quoi qu'il en soit, je serais heureux de jouer au testeur pour ces traductions.
Serait-il possible de se contacter par mail ou par discord ?

**Comment by LoganTann** [comment]
Ce serait aussi sympa de faire un petit utilitaire pour vérifier les mises à jour de ces traductions
après ce n'est pas forcément la priorité

**Comment by L-Sherry** [comment]
Bonjour,

Pour la langue, on va dire qu'on s'en fout. J'accepte l'anglais, le français et même l'allemand pas trop stéréotypé.

Les commits arrivent, mais au rythme ou ça va, va falloir attendre avant d'avoir ne serait-ce que 50% du jeu traduit. Globalement, je suis plutôt en mode "au diable les mines, en avant toutes" pour essayer d'avancer plus vite, donc des fautes, va y en avoir. D'ailleurs, les derniers commits, je les ai même pas testés, je crois.

J'imagine que la traduction du 15 juin, c'est 02dc58983. J'ai déjà du corriger des fautes de seconde personne du singulier à coup de chercher/remplacer, bien qu'à terme il faudrai que je trouve le moyen de faire tourner genre un Grammalectre sur mes traductions.

Sinon le chapitre 6 à 8 ça doit faire partie des quelques chapitres ou y a un peu de traductions, et encore. Je traduit principalement des lieux, dans l'ordre chronologique ou ils apparaissent, mais tout ce qui se passe dans ce lieu y passe, donc tout ce qui se passe sur le navire est déjà traduit. Il doit peut-être y avoir les dialogues avec apollo, qui eux ne sont pas liés à un lieu, et que je n'ai jamais testés, en plus.

- Pour Thé vert, on va dire que j'accepte. Le jeu reste ambigu entre "Thé au feuilles vertes" et "Feuilles de Thé Vert" (sous entendu on mange les feuilles, mais ça colle pas avec l'icone ...)
- Le rond de pain c'est plutôt un Brötchen/Bun dans la version originale, faudrai plutôt le traduire en "petit pain" ou "pain rond" (le deuxième étant plus court ...)
- Pour botanics je prend.
- Pour Viel Os vs Vieux Os, l'original est au pluriel ... Et comme pour la plupart des items, je saisi pas la référence.

- Je prend la correction pour "prends ça", mais je suis globalement pas encore satisfait de cette traduction (bien qu'elle soit pas marquée bad, parce que c'est que très récement que je peux marquer ces traductions comme bad). L'original c'est genre "Bouncer", j'ai du aller chercher la trad allemande pour trouver ça ...
- "ma conclusion tiens encore", oui c'est une faute d'accord, d'ailleurs, faudrai plutôt dire "ma conclusion tient toujours" (les avatars c'est de la camelote).

Le reste, faut que je le lise et corrige plus tard, possiblement quand il fera moins chaud.

**Comment by L-Sherry** [comment]
- Je sais pas encore pour "ce qui allait arriver" vs "ce qui allait t'arriver", d'ailleurs, si je traduisais littéralement l'allemand, ça serait "ce qui se passerai".

- "tu peux faire voir à lea quelques trucs" je sais pas d'ou j'ai sorti ça... l'original parle juste de faire visiter un peu.

- "secoue la tête" et "acquiesce" ça fait partie des deux choses dont je ne suis toujours pas sur pour les traductions. j'hésitais d'ailleurs à utiliser "hoche" pour oui. En tout cas, l'anglais et l'allemand utilisent tout les deux une traduction de secouer pour dire non, donc je sais pas ...

- "routine" c'est déjà dans la version originale ... et pas qu'une fois.

- "agile et lour", la seule chose que je retrouve, c'est "Agile et lourdement armé !", ça s'affiche pas bien ? j'ai jamais fait gaffe à la taille des textes des side_msg, mais celui là c'est loin d'être le plus long, donc c'est bizarre. J'ai jamais testé ces traductions, d'autant que ça fait partie des toutes premières que j'ai faites (avant même d'avoir essayer de faire que le jeu puisse les afficher). Je teste surtout le jeu dans l'ordre chronologique.

Je sais pas quelles phrases manquent de majuscules, mais celles qui sont coupées par des "...", j'ai tendance à ne pas mettre de majuscules quand elles reprennent, un peu parce que le jeu original n'en met pas non plus.

Pour le reste, j'ai normalement tout corrigé, j'ai cherché toutes les autres fautes dans le genre futur/conditionel présent, et des "est ce", et j'en ai trouvé déjà plein. et j'ai corrigé encore d'autres trucs en les survolant...

J'ai mis le mail qui était déjà dans mes commits comme public dans mon profil Github. Pour discord, j'ai déjà essayé de créer un compte et outre avoir passé plein de captcha chiants, il fini par me dire que mon compte est flaggé et qu'il veut mon numéro de téléphone ...non mais oh.

Vu que j'ai moins de problèmes avec mes scripts, je devrai pouvoir pousser des maj plus souvent.

**Comment by Wilfride123** [comment]
bonjour je ne sais pas vraiment si sait adapter de demander de demander ca ici donc dsl en avance: je voudrais aider pour la traduction.... mais j'ai quelque petit problème 1.... je suis une quiche pour l'ortographe ^^;.....et 2.... j'ai pas encore le jeux ^^;;;(mais sa se sera réglé début du prochain mois).... donc je pourrais surtout servir de cobaye....l'avantage c'est que J'ADORE parler avec tout les png qui passe ^^ donc voilà.....et dsl si j'aurais du ouvrir un nouveau sujet..... j'ai pas l'habitude avec ce site ^^;

**Comment by LoganTann** [comment]
@Wilfride123 hey~Je ne contribue pas vraiment au projet mais je pense que je pourrais quand même te conseiller.
Pour le moment l'objectif est de traduire au maximum le jeu, peu importe l'orthographe (mais les trads doivent rester fiables !). Ensuite, une fois cet objectif fait, nous tenterons de chercher des fautes. Pour le moment aucun rôle n'est assigné mais je me ferais un plaisir de recommencer le jeu pour chercher les fautes.

Est-ce que tu as des connaissances en programmation? Aussi, est-ce que tu sais te servir de linux ?
Ces deux choses ne sont pas importantes mais maîtrisées, elle pourraient te faire gagner du temps.
En effet, il le semble que la contribution aux traductions se fera non pas dans des logiciels spécialisé mais dans des sortes de fichiers de code (json).

A ce que je vois tu ne sais pas utiliser git et github. Je pourrais aussi tenter de t'apprendre à utiliser ça.
Si tu es ici, tu as probablement discord ? Si oui, on peut se contacter (@ShinProg#2885) ou à défaut par mail.

Par ailleurs @L-Sherry je me demande si c'est possible d'adapter un support des traductions via un logiciel comme http://zanata.org/

**Comment by Wilfride123** [comment]
@Logan Tann et bien dan l'ordre:Non,non, quand je disais que je ne sais pas utiliser github saiter plutôt dans le sens que j'ai jamais vraiment utilisé le site,oui et bien sur (@Max"wilfride"maxy#2112).... voilà ^^;

**Comment by LoganTann** [comment]
Ah j'avais oublié de dire je suis absent du 14 au 28 juillet donc je verrais ton cas en aout :)

**Comment by L-Sherry** [comment]
Bonjour,

Pour zanata ou autre, la seule vraie question, c'est est ce que il y a un moyen de garder ça accessible que au gens qui ont le jeu. parce que si je balance tout les textes du jeu comme ça sur le net, je suis pas sûr que les développeurs apprécient franchement.

Pour l'instant je balance tout en pseudo-chiffé histoire que les données du jeu soient nécessaire pour déchiffrer... 

Pour le reste, localize-me-tools à quand même pas mal de fonctionnalités spécifiques dont je suis pas sûr qu'elles soient disponible dans un logiciel générique, genre le de gérer facilement les 10000 textes dupliqués ou de vérifier la syntaxe des références...

**Comment by L-Sherry** [comment]
Bon, après avoir :
- Corrigé plein de fautes
- Passé grammalecte sur mes traductions, et corrigé encore bien plus de fautes
- Vérifié que "Agile et lourdement armé !" s'affiche correctement (j'ai pas réussi à reproduire le problème, mais j'imagine bien un bug lié à la version vulnérable de cryptojs que le jeu utilise)

Je pense qu'on peut considérer ce bug comme étant corrigé.

**Comment by LoganTann** [comment]
Bravo !! 
Je suis vraiment peu disponible donc je ne peux pas tester les traductions en ce moment, trop de projets persos associés à moins de temps libre l'oblige... Mais si je me remet à jouer au jeu, j'y penserai !
Apparemment, d'après les commits, la traduction du jeu a entièrement été finie. Félicitations !!
