### ISSUE TITLE
Jean de la quête "lapin légendaire"

### ISSUE THREAD

**Issue by klownk** [L-Sherry/French-CC#12]
Quand on revient pour lui donner les carottes congelées, son texte est complètement en anglais.
![image](https://user-images.githubusercontent.com/20015863/147420447-d57aeaf8-f0a3-49ab-a6ff-65cb5bb742dd.png)

**Comment by L-Sherry** [comment]
Bonjour,

Vu d'ici, j'ai l'impression que French-CC n'est pas à la dernière version. Vous utilisez quelle version de CrossCode et French-CC ?

**Comment by klownk** [comment]
Hé bien, la dernière version que vous proposez ici. La 1.2.0.
