### ISSUE TITLE
Error : unsupported var access path : area.rhombus-square.name

### ISSUE THREAD

**Issue by LoganTann** [L-Sherry/French-CC#2]
![Capture d’écran_2019-06-27_18-23-54](https://user-images.githubusercontent.com/28659185/60284220-4b634e00-990b-11e9-9f7e-27006581c866.png)

Le jeu crashe lors d'un dialogue après avoir obtenu le Meteor Shade.
J'ai fait le test sans CC-Loader et pas de crash ce qui me prouve que cela est causé par un mod; je suppose que c'est celui-ci...

Pour reproduire le bug, il faut battre le vagabond (=> finir la quête Trial of the Golden Bugs); j'envoie une copie de ma sauvegarde ici : 
[Importsave.txt](https://github.com/L-Sherry/French-CC/files/3335846/Importsave.txt)

Pour importer la sauvegarde, il suffit de copier son contenu, aller dans Écran d'accueil-> Charger une partie -> touche F10 -> textarea "Import Save Slot" et coller le contenu précédemment copier

**Comment by L-Sherry** [comment]
Oui c'est marrant dans ce jeu, quand tu fais une mauvaise traduction, le jeu plante, et encore, pas toujours. (c'est area.rhombus-sqr.name et pas area.rhombus-square.name).

Je devrai avoir corrigé celle là, mais faut vraiment que je code un truc qui les vérifient.
