### ISSUE TITLE
Langue française disparue ?

### ISSUE THREAD

**Issue by LoganTann** [L-Sherry/French-CC#3]
Bonjour,
je me suis remis à jouer au jeu mais comme la plupart des fois, je pense toujours à refaire un git pull afin de mettre à jour le fichier de traduction.
Sauf que après ce git pull, la langue française ne fonctionne plus pour une raison que j'ignore...
j'ai testé avant (ça fonctionnait) mais je n'ai malheureusement pas la référence du commit lorsque tout fonctionnait.

![Capture d’écran_2019-08-07_20-52-03](https://user-images.githubusercontent.com/28659185/62650160-86b75a80-b956-11e9-955e-74d93ff517e0.png)
![Capture d’écran_2019-08-07_20-52-14](https://user-images.githubusercontent.com/28659185/62650161-86b75a80-b956-11e9-82c9-f5d4b149b306.png)

**Comment by L-Sherry** [comment]
Est-ce que Localize Me est à la derniere version ?
(il me semble que CCLoader est assez silencieux lorsque une dépendance n'est pas satisfaite, si je me souviens bien)

**Comment by LoganTann** [comment]
Bonjour,
oui en effet, le problème a été résolu avec ce que vous m'avez proposé !
merci !!

**Comment by LoganTann** [comment]
par ailleurs j'ai fini le jeu donc je suis prêt à le recommencer pour tester les trads lorsqu'elles seront finies

**Comment by L-Sherry** [comment]
Je viens de tester ce cas avec la dernière version de CCLoader, et j'ai au moins un message d'erreur quand il y a pas la bonne dépendance. Après, le message d'erreur ne donne pas beaucoup d'indication sur ce qui ne va pas...

Pour les trads, normalement tout est traduit du début du jeu jusqu'à Bergen. Sauf les entrées de l'encyclopédie et d'autres petit trucs, peut-être.

(sinon pour voir l'historique de tes pulls, il y a git reflog --date=local )
