### ISSUE TITLE
Relevé d'erreurs

### ISSUE THREAD

**Issue by ArcheoCodix** [L-Sherry/French-CC#6]
Salut,

Merci mille fois pour ce patch FR, j'ai eu du mal à le trouver mais maintenant que je l'ai c'est un plaisir.
Je viens d'attaquer le jeu et j'ai pu relever certaines choses, donc j'utilise cette issue pour les partager.
Je pense (si c'est possible), utiliser cette issue pour partager les fautes durant toute ma partie et apporter mon caillou au monument.

Voici ce que j'ai pu trouver pour l'instant :

Près -> prête ?
![image](https://user-images.githubusercontent.com/26336032/71937692-6ada0e00-31ad-11ea-90f5-cab11c14c54c.png)

Je ne suis pas sûr pour celle-la mais ça devrait être ceinture ou "bassin" ou quelque chose comme ça non ?
![image](https://user-images.githubusercontent.com/26336032/71937743-86ddaf80-31ad-11ea-85e8-29042bb13de0.png)

"survire" Faute de frappe ;) 
![image](https://user-images.githubusercontent.com/26336032/71937751-8c3afa00-31ad-11ea-96e3-3260a7097517.png)

Voilà.
Je peux, évidemment, me tromper.

Merci encore !

**Comment by L-Sherry** [comment]
J'ai corrigé le premier et le dernier, mais j'ai pas compris le deuxième. C'est "torse" le problème ? Parce que c'est aussi comme ça dans la version originale, il faut pas trop prendre les équipements au sérieux dans ce jeu de toutes façon.

**Comment by ArcheoCodix** [comment]
J'ai remarqué par la suite que ça comprend tout donc pas de problème.
Oui, il y a de tout mais surtout du n'importe quoi haha.

**Comment by ArcheoCodix** [comment]
J'ai vu par la suite que ça comprenait tout donc pas de problème.
Oui j'ai vu qu'il y avait de tout mais surtout du n'importe quoi en équipement haha.
